### ISSUE TITLE
[ Bug ] windows标题栏错位

### ISSUE THREAD

**Issue by ThereIsNothingHere** [std-microblock/chromatic#560]
### Bug 描述

如图，最小化最大化和关闭按钮错位

### 复现步骤

装完就有

### 期望行为

修复错位

### 屏幕截图

![Image](https://github.com/user-attachments/assets/a29e782c-0d10-4b78-8d63-85ed937b0cb2)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

3.1.5

### 网易云音乐 Patch 版本

2344573

**Comment by Zellon0w0** [comment]
同题主，标题栏错位

![Image](https://github.com/user-attachments/assets/b8026b0f-f334-400c-8717-0051efbbe815)

**Comment by bg3h** [comment]
SAME +1

**Comment by wangmumu0601** [comment]
临时解决办法：

插件商城下载 StyleSnippet 插件

在Local 本地的+ 中 添加 id 为`page_pc_main_nav`，打开此配置开关

打开本地`C:\betterncm\StyleSnippets`文件夹(若更改了此地址请自行寻找) 可以看见上一步新建的`page_pc_main_nav.less`文件，在其中输入下面代码，保存后关闭记事本，重启网易云音乐
```less
#page_pc_main_nav div div.IconBar_i1ueu1yn div.Divider_d1jt85zx {
    margin-right: 0;
}
```


![Image](https://github.com/user-attachments/assets/44323018-a98c-45d6-8e05-e38c06520486)
